#!/bin/sh
# Start Entware services (if installed on SD card)
[ -x /opt/etc/init.d/rc.unslung ] || exit 0
case "$1" in
  start) /opt/etc/init.d/rc.unslung start ;;
  stop)  /opt/etc/init.d/rc.unslung stop ;;
esac
